### ISSUE TITLE
vim-gnome does not exist on ubuntu-latest

### ISSUE THREAD

**Issue by lelutin** [rhysd/action-setup-vim#15]
Hi, I've just setup a workflow using this action and the `apt install` command for vim latest fails saying that the `vim-gnome` package does not exist.

It's a bit strange to me to install a graphical interface to vim to run tests in a headless container. I suggest the action changes to installing `vim-nox` instead, which should be available in all releases of ubuntu.

**Comment by rhysd** [comment]
What version of Ubuntu do you use? And if the repository is public, providing the link is helpful.

Expected behavior is:

- When the worker is Ubuntu 19.04 or earlier, it installs `vim-gnome` for compatibility
- When the worker is Ubuntu 20.04 or later, it installs `vim-gtk` since `vim-gnome` was removed

Ref: https://github.com/rhysd/action-setup-vim/blob/master/CHANGELOG.md#v127---05-feb-2021

> I suggest the action changes to installing vim-nox instead, which should be available in all releases of ubuntu.

I considered the point in the past. Since `vim-nox` is a minimal package for environment where X is not installed, it disables some features. It may prevent some plugins which use them. Anyway, I can investigate this issue when I understand what version of Ubuntu I should try.

**Comment by rhysd** [comment]
I checked your repository and found that you use a bit older version of action-setup-vim.

https://github.com/lelutin/vim-puppet/commit/767977bf7e32fcced9ad509721e4d49b91337d57#diff-69c88d2eac6e4a39335142160f7b2c5d159b6c9a662395d16d77dc45f0a4677dL23

Please use the latest version (v1.2.7) which fixed this issue. I recommend to use `v1` tag instead of specific version.

```yaml
- name: Setup Vim or Neovim
  uses: rhysd/action-setup-vim@v1.2.7
  id: vim
  with:
    neovim: ${{ matrix.neovim }}
```

**Comment by lelutin** [comment]
ah! thanks for the insightful feedback! (and sorry for the original lack of context)

I'm currently trying this out to see if I'll get it to work, but the job is getting consistently canceled without any reason mentioned... I've contacted github support to know how to go about fixing this.
